analyze_web_performance_task:
  description: >
    Analyze the performance of "{website_url}" using the tool provided.
    Provide insights on the following:
    - Overall performance score.
    - Key metrics.
    - Opportunities for improvement and diagnostics.
    If you don't have enough data generate a brief summary of the input.
    IMPORTANT: Always provide output!

  expected_output: >
    A summarized report including:
    - The performance score (0–100).
    - Key metrics of performance and their values.
    - A summary of improvement opportunities and diagnostics.
    - Suggestions to improve the web page's performance.
  agent: pagePerformance_analyzer
  inputs:
    website_url: "{website_url}"
  

analyze_web_accessibility_task:
  description: >
    Analyze the accessibility of "{website_url}" using the tool provided.
    Provide insights on the following:
    - Overall accessibility score.
    - Key metrics.
    - Opportunities for improvement and diagnostics.
    If you don't have enough data generate a brief summary of the input.
    IMPORTANT: Always provide output!

  expected_output: >
    A summarized report including:
    - The accessibility score (0–100).
    - Key metrics and their values.
    - A summary of improvement opportunities and diagnostics.
    - Suggestions to improve the web page's accessibility.
  agent: pageAccessibility_analyzer
  inputs:
    website_url: "{website_url}"

analyze_web_best_practices_task:
  description: >
    Analyze the best-practices of "{website_url}" using the tool provided.
    Provide insights on the following:
    - Overall compliance to best-practices score.
    - Key metrics.
    - Opportunities for improvement and diagnostics.
    If you don't have enough data generate a brief summary of the input.
    IMPORTANT: Always provide output!


  expected_output: >
    A summarized report including:
    - The compliance score (0–100).
    - Key metrics and their values.
    - A summary of improvement opportunities and diagnostics.
    - Suggestions to improve the web page's compliance to best-practices.
  agent: pageBestPractices_analyzer
  inputs:
    website_url: "{website_url}"


reporting_task:
  description: >
    Review the context you got from all agents and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A summarized reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
